### PR TITLE
Bump ES6 to ES8

### PR DESCRIPTION
**Pull request by 131**
I'll suggest to publish this a a semver major ?

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
we should probably have a test, what's being added in 8, async await ?

**Comment by 131** [comment]
With a dummy test

**Comment by calvinmetcalf** [comment]
Sweet will deal with this tomorow

**Comment by calvinmetcalf** [comment]
why do you suggest semver major? I'm strugling to think of code that this would previously work with that wouldn't now

**Pull request merged**
